### PR TITLE
fix missing curly braces

### PR DESCRIPTION
**Pull request by x5engine**

### CODE REVIEW

**Comment by oed** [comment]
@oznekenzo @zachferland Can you have a look at this and merge / release? :)

**Comment by x5engine** [comment]
also this plugin doesnt work on nextjs!

**Comment by oed** [comment]
Hey @x5engine Can you describe what issue this solves? Was there an error happening before you made this change?

**Comment by x5engine** [comment]
yes if you tried that it will throw a syntax error, just check it and you will see its missing a curly braces

**Review by oed — APPROVED** [review]
Makes sense, Thanks for making this PR :)

**Comment by x5engine** [comment]
no worries :)

**Pull request merged**
